/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Formularios.CapturaHuella;
import Formularios.Funcionarios;
import clases.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author Rec Tecnologicos
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
        
    public MainFrame() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
  
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horaLabel = new rojeru_san.RSLabelHora();
        fechaLabel = new rojeru_san.RSLabelFecha();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrar = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        horaLabel.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N

        fechaLabel.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        fechaLabel.setFormato("yyyy-MM-DD");

        jMenu1.setText("Administrador");

        menuRegistrar.setText("Registrar Funcionario");
        menuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuRegistrar);

        menuCerrar.setText("Cerrar");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funcionarios");

        jMenuItem1.setText("Todos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(horaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        if (validarAdministrador()) {
            System.exit(0);                    
        }        
    }//GEN-LAST:event_menuCerrarActionPerformed

    private void menuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarActionPerformed
        if (validarAdministrador()) {
            new CapturaHuella().setVisible(true);
        }
    }//GEN-LAST:event_menuRegistrarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //new CapturaHuellaIngreso(this, true).setVisible(true);
    }//GEN-LAST:event_formComponentShown

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Funcionarios(this, false).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public boolean validarAdministrador(){
        
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Ingrese Contraseña de Administrador");
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Administrador",
                              JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                              null, options, options[1]);
        pass.setFocusable(true);
        pass.requestFocus();
        if(option == 0) // pressing OK button
        {
            char[] password = pass.getPassword();
            //String password = pass.getText();
            String passadmin = new String(password);
            //System.out.println("Your password is: " + new String(password));
            ConexionBD con = new ConexionBD();
            //con.conectar();

            try {
                ResultSet consulta = con.consultar("Select estado from administrador where pass = SHA('"+passadmin+"');");
                String estado="";
                //con.cerrar();
                while (consulta.next()) {                
                    estado = consulta.getString("estado");
                }
                if ("activo".equals(estado)) {
                    return true;
                }
                //System.out.println(estado);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Throwable ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.RSLabelFecha fechaLabel;
    public rojeru_san.RSLabelHora horaLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenuItem menuRegistrar;
    // End of variables declaration//GEN-END:variables
}
