/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.ConexionBD;
import clases.Estadisticas;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Rec Tecnologicos
 */
public class verEstadisticasCopia extends javax.swing.JDialog {

    private final String numdoc;
    ConexionBD con = new ConexionBD();

    /**
     * Creates new form verEstadisticas
     * @param parent
     * @param modal
     * @param numdoc
     */
    public verEstadisticasCopia(java.awt.Frame parent, boolean modal, String numdoc) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.numdoc = numdoc;
        
        setFoto();
        setDatos();
        setEstadisticas();
        sumaHoras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelFoto = new javax.swing.JPanel();
        fotoFuncionario = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelDependencia = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ultimoRegistro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        horasDiferencia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        promSemanal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        razon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        observacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estadisitcas");

        panelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre.setText("Nombre");

        labelCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCorreo.setText("Correo");

        labelCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCedula.setText("Cedula");

        labelDependencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDependencia.setText("Dependencia");

        labelCargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCargo.setText("Cargo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas"));

        jLabel7.setText("Último Registro:");

        ultimoRegistro.setText("jLabel8");

        jLabel9.setText("Horas Diferencia:");

        horasDiferencia.setText("jLabel10");

        jLabel11.setText("Prom. Horas Semanales:");

        promSemanal.setText("jLabel12");

        jLabel2.setText("Razón");

        razon.setText("jLabel3");

        jLabel3.setText("Observación");

        observacion.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ultimoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(horasDiferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(promSemanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(razon)
                    .addComponent(observacion))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ultimoRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(razon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(observacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(horasDiferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(promSemanal))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(labelCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDependencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCargo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public final void setDatos(){
        try {
            String sql = "SELECT nombre, correo, dependencia, cargo FROM funcionarios where numdoc = "+numdoc+" LIMIT 1";
            
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet result = pst.executeQuery();

            while(result.next()){
                labelCedula.setText(String.valueOf(numdoc));
                labelNombre.setText(result.getString(1));
                labelCorreo.setText(result.getString(2));
                labelDependencia.setText(result.getString(3));
                labelCargo.setText(result.getString(4));  
            }
        } catch (SQLException ex) {
            Logger.getLogger(verEstadisticasCopia.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    public final void setEstadisticas(){
        try {
            String sql = "SELECT hora, fecha, tipo, razon, observacion FROM registros where numdoc = "+numdoc+" order by idregistros desc LIMIT 1";
            
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet result = pst.executeQuery();

            while(result.next()){
                ultimoRegistro.setText(result.getString(3)+" "+result.getString(1)+"   "+result.getString(2));
                razon.setText(result.getString(4));
                observacion.setText(result.getString(5));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(verEstadisticasCopia.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    public final void setFoto(){
        try {
            
            String sql = "SELECT foto FROM funcionarios where numdoc = "+numdoc+" LIMIT 1";

            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet result = pst.executeQuery();

            while(result.next()){
                //byte[] imagen = result.getBytes("foto");
                Blob blob = result.getBlob(1);
            //primero me aseguro que no este vacío.
            if(blob != null){
               try{
              byte[] data = blob.getBytes(1, (int)blob.length());
              BufferedImage img = null;

              try{
                img = ImageIO.read(new ByteArrayInputStream(data));
              }
              catch(IOException ex){
                System.out.println(ex.getMessage());
              }

             ImageIcon icono = new ImageIcon(img.getScaledInstance(282, 210, Image.SCALE_SMOOTH));

             //JOptionPane.showMessageDialog(null, "Imagenes", "Imagen", JOptionPane.INFORMATION_MESSAGE, icono);

             fotoFuncionario.setIcon(icono);

              }catch(SQLException ex){
                   System.out.println(ex.getMessage());
              }
            }
            else{
                System.out.println("No hay foto");
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Funcionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public final void sumaHoras(){
        try {
            
            Calendar ca1endar = Calendar.getInstance();
            String hour = Integer.toString(ca1endar.get(Calendar.HOUR));
            String minuto = Integer.toString(ca1endar.get(Calendar.MINUTE));
            
            String dia = Integer.toString(ca1endar.get(Calendar.DATE));
            String mes = Integer.toString(ca1endar.get(Calendar.MONTH)+1);
            String annio = Integer.toString(ca1endar.get(Calendar.YEAR));
            
            
            mes = String.format("%2s", mes).replace(' ','0');
            minuto = String.format("%2s", minuto).replace(' ','0');
            
            String fecha = annio+"-"+mes+"-"+dia;
            minuto = String.format("%2s", minuto).replace(' ','0');
            String hora = hour+":"+minuto+":00";
            Time horaactual = Time.valueOf(hora);
            
            
            String sql = "SELECT count(idregistros) FROM registros where tipo='Entrada' and numdoc = "+numdoc+" and  fecha between (select inicio from semanas where '"+fecha+"' between inicio and fin) and (select fin from semanas where '"+fecha+"' between inicio and fin) order by idregistros asc";
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet result = pst.executeQuery();
            int resultadosEnt = 0;
            while(result.next()){
                resultadosEnt = result.getInt(1);
            }
            
            sql = "SELECT count(idregistros) FROM registros where tipo='Salida' and numdoc = "+numdoc+" and  fecha between (select inicio from semanas where '"+fecha+"' between inicio and fin) and (select fin from semanas where '"+fecha+"' between inicio and fin) order by idregistros asc";
            pst = con.getConexion().prepareStatement(sql);
            result = pst.executeQuery();
            int resultadosSal = 0;
            while(result.next()){
                resultadosSal = result.getInt(1);
            }
            
            sql = "SELECT hora, tipo FROM registros where numdoc = "+numdoc+" and  fecha between (select inicio from semanas where '"+fecha+"' between inicio and fin) and (select fin from semanas where '"+fecha+"' between inicio and fin) order by idregistros asc";
            System.out.println(sql);
            pst = con.getConexion().prepareStatement(sql);
            result = pst.executeQuery();
            
            if (resultadosEnt>resultadosSal) {
                resultadosSal += 1;
            }

            Time[] entradas = new Time[resultadosEnt];
            Time[] salidas = new Time[resultadosSal];
            int i = 0;
            int j = 0;
            
            
            while(result.next()){
                if (result.getString(2).equals("Entrada")) {
                    entradas[i] = result.getTime(1);
                    i++;
                }
                else{
                    salidas[j] = result.getTime(1);
                    j++;
                }
            }
            if (salidas[resultadosSal - 1] == null) {
                //salidas[resultadosSal - 1] = horaactual;
                salidas[resultadosSal - 1] = horaactual;
            }
            
            Time diferencia = null;
            int sumatoria = 0;
            
            System.out.println("Nueva consulta");
            for (int k = 0; k < resultadosEnt; k++) {
                
                diferencia = Estadisticas.getDifferenceBetwenDates(entradas[k], salidas[k]);
                
                sumatoria += (diferencia.getHours()*60)+diferencia.getMinutes();
                
            }
            if (diferencia == null){
                horasDiferencia.setText("");
            }
            else{
                horasDiferencia.setText(diferencia.toString());
            }
            promSemanal.setText((sumatoria/60)+":"+(sumatoria%60));
        } catch (SQLException ex) {
            Logger.getLogger(verEstadisticasCopia.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                verEstadisticas dialog = new verEstadisticas(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fotoFuncionario;
    private javax.swing.JLabel horasDiferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDependencia;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel observacion;
    private javax.swing.JPanel panelFoto;
    private javax.swing.JLabel promSemanal;
    private javax.swing.JLabel razon;
    private javax.swing.JLabel ultimoRegistro;
    // End of variables declaration//GEN-END:variables
}
