/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import clases.ConexionBD;
import clases.Estadisticas;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rec Tecnologicos
 */
public class verRegistrosMes extends javax.swing.JDialog {

    String numdoc;
    ConexionBD con;
    String meses[] = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    public String fecha;
    public Time horaactual;
    public String mes;
    DefaultTableModel modelo;
    
    /**
     * Creates new form verRegistrosMes
     * @param parent
     * @param modal
     * @param numdoc
     */
    public verRegistrosMes(java.awt.Frame parent, boolean modal, String numdoc) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.numdoc = numdoc;
        con = new ConexionBD();
        Calendar ca1endar = Calendar.getInstance();
        String hour = Integer.toString(ca1endar.get(Calendar.HOUR));
        String minuto = Integer.toString(ca1endar.get(Calendar.MINUTE));

        String dia = Integer.toString(ca1endar.get(Calendar.DATE));
        mes = Integer.toString(ca1endar.get(Calendar.MONTH)+1);
        String annio = Integer.toString(ca1endar.get(Calendar.YEAR));


        mes = String.format("%2s", mes).replace(' ','0');
        minuto = String.format("%2s", minuto).replace(' ','0');

        fecha = annio+"-"+mes+"-"+dia;
        minuto = String.format("%2s", minuto).replace(' ','0');
        String hora = hour+":"+minuto+":00";
        horaactual = Time.valueOf(hora);
        
        modelo =(DefaultTableModel) tablaRegistros.getModel();
        setDatos();
        setFilas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "H. Entrada", "H. Salida", "Diferencia", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRegistros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Registros por mes: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelFuncionario.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDatos(){
        try {
            String sql = "Select nombre from funcionarios where numdoc = "+numdoc+" limit 1";
            PreparedStatement pst = con.getConexion().prepareStatement(sql);
            ResultSet result = pst.executeQuery();
            while (result.next()) {                
                labelFuncionario.setText(result.getString(1));
            }
            
            labelTitulo.setText(labelTitulo.getText() + meses[Integer.parseInt(mes)-1]);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(verRegistrosMes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setFilas(){
        String where = "numdoc = "+numdoc+" and MONTH(fecha) = '"+mes+"'";
        Estadisticas estadisticas = new Estadisticas(where);
        
        Vector<Time> vEntradas = estadisticas.getvEntradas();
        Vector<Time> vSalidas = estadisticas.getvSalidas();
        Vector<Date> vFechas = estadisticas.getvFechas();
        
        Time diferencia = null;
        
        if (vEntradas.size()>vSalidas.size()) {
            vSalidas.add(null);
        }
        Object datos[]=new Object[4];
        for (int k = 0; k < vEntradas.size(); k++) {
            if (vSalidas.elementAt(k) == null) {
                diferencia = null;
            }
            else{
                diferencia = Estadisticas.getDifferenceBetwenDates(vEntradas.elementAt(k), vSalidas.elementAt(k));
            }
            
            System.out.println(vEntradas.elementAt(k));
            datos[0] = vEntradas.elementAt(k);
            datos[1] = vSalidas.elementAt(k);
            datos[2] = diferencia;
            datos[3] = vFechas.elementAt(k);
            
            modelo.addRow(datos);
//            tablaRegistros.setValueAt(vEntradas.elementAt(k), k, 0);    
//            tablaRegistros.setValueAt(vSalidas.elementAt(k), k, 0);
//            tablaRegistros.setValueAt(diferencia, k, 0);
//            tablaRegistros.setValueAt(vFechas.elementAt(k), k, 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables
}
